version: '3'
services:
  
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: "neo4j/test_password" # Usuario y contraseña
    ports:
      - "7474:7474"  # Puerto para la interfaz web
      - "7687:7687"  # Puerto para las conexiones Bolt (usado por la API)

  api:
    build: ./api
    container_name: python-api
    ports:
      - "5000:5000"  # Puerto para la API
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test_password
